import MemcpyProof.Elf
import MemcpyProof.RV32I

open MemcpyProof.Elf
open MemcpyProof.RV32I

/-- Hex pretty-print with a left-pad width. -/
def hex (n : Nat) (width : Nat := 8) : String :=
  let s := String.ofList (Nat.toDigits 16 n)
  "".pushn '0' (width - s.length) ++ s

/-- Generate `Extract.lean`: the encoded code as a Lean constant + a
    `code : UInt32 → UInt32` lookup. -/
def emitExtract (out : System.FilePath) (vaddr : UInt32) (mb : ByteArray) : IO Unit := do
  let mut lines : Array String := #[]
  lines := lines.push "/- AUTO-GENERATED by `lake exe extract --emit`. Do not edit. -/"
  lines := lines.push "namespace MemcpyProof.Extract"
  lines := lines.push ""
  lines := lines.push s!"def vaddr : UInt32 := 0x{hex vaddr.toNat}"
  lines := lines.push s!"def numInstrs : Nat := {mb.size / 4}"
  lines := lines.push ""
  lines := lines.push "/-- The memcpy routine as a list of 32-bit little-endian instruction words. -/"
  lines := lines.push "def words : List UInt32 := ["
  let n := mb.size / 4
  for i in [0:n] do
    let w := u32le mb (4*i)
    let sep := if i + 1 == n then "" else ","
    lines := lines.push s!"  0x{hex w.toNat}{sep}"
  lines := lines.push "]"
  lines := lines.push ""
  lines := lines.push "/-- Direct PC-to-word lookup, structured as a `match` on UInt32"
  lines := lines.push "    so the kernel can pattern-match `code <literal pc>`. -/"
  lines := lines.push "def code : UInt32 → UInt32"
  for i in [0:n] do
    let w := u32le mb (4*i)
    let a := vaddr.toNat + 4*i
    lines := lines.push s!"  | 0x{hex a} => 0x{hex w.toNat}"
  lines := lines.push "  | _ => 0"
  lines := lines.push ""
  lines := lines.push "/-- Per-PC equations, proved by `native_decide` so the kernel doesn't"
  lines := lines.push "    have to walk the entire `match`.  Use these as rewrite lemmas"
  lines := lines.push "    inside proofs. -/"
  for i in [0:n] do
    let w := u32le mb (4*i)
    let a := vaddr.toNat + 4*i
    lines := lines.push s!"theorem code_at_{hex a} : code 0x{hex a} = 0x{hex w.toNat} := by native_decide"
  lines := lines.push ""
  lines := lines.push "end MemcpyProof.Extract"
  IO.FS.writeFile out (String.intercalate "\n" lines.toList ++ "\n")

def main (args : List String) : IO UInt32 := do
  let mut path : String := "/workspace/client.elf"
  let mut emit : Bool := false
  let mut emitPath : System.FilePath := "/workspace/memcpy-proof/MemcpyProof/Extract.lean"
  let mut rest : List String := args
  while !rest.isEmpty do
    match rest with
    | "--emit" :: xs => emit := true; rest := xs
    | "--out" :: p :: xs => emitPath := p; rest := xs
    | p :: xs => path := p; rest := xs
    | [] => rest := []

  let bytes ← IO.FS.readBinFile path
  match parseHeader bytes with
  | .error e => IO.eprintln s!"parse error: {e}"; return 1
  | .ok elf =>
    match findSymbol elf "memcpy" with
    | none => IO.eprintln "memcpy not found"; return 2
    | some sym =>
      let size := if sym.size.toNat == 0 then (0x200d04 - 0x2008f8) else sym.size.toNat
      match symbolBytes elf sym size with
      | .error e => IO.eprintln s!"slice error: {e}"; return 3
      | .ok mb =>
        if emit then
          emitExtract emitPath sym.value mb
          IO.println s!"wrote {emitPath} — {mb.size / 4} instrs, vaddr 0x{hex sym.value.toNat}"
        else
          IO.println s!"memcpy @ 0x{hex sym.value.toNat} — {mb.size} bytes ({mb.size / 4} instrs)"
          IO.println ""
          let mut other := 0
          for i in [0:mb.size / 4] do
            let w := u32le mb (4*i)
            let ins := decode w
            let addr := sym.value.toNat + 4*i
            let isOther := match ins with | .other _ => true | _ => false
            if isOther then other := other + 1
            IO.println s!"  0x{hex addr 6}:  {hex w.toNat}   {Instr.pp ins}"
          IO.println ""
          IO.println s!"unrecognized: {other}"
        return 0
